/**
 * OrganizationServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.evolveum.polygon.connector.liferay.organization;

public interface OrganizationServiceSoap extends java.rmi.Remote {
    public void addGroupOrganizations(long groupId, long[] organizationIds) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap addOrganization(long parentOrganizationId, java.lang.String name, java.lang.String type, boolean recursable, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.AddressSoap[] addresses, com.evolveum.polygon.connector.liferay.organization.EmailAddressSoap[] emailAddresses, com.evolveum.polygon.connector.liferay.organization.OrgLaborSoap[] orgLabors, com.evolveum.polygon.connector.liferay.organization.PhoneSoap[] phones, com.evolveum.polygon.connector.liferay.organization.WebsiteSoap[] websites, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap addOrganization(long parentOrganizationId, java.lang.String name, java.lang.String type, boolean recursable, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap addOrganization(long parentOrganizationId, java.lang.String name, java.lang.String type, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.AddressSoap[] addresses, com.evolveum.polygon.connector.liferay.organization.EmailAddressSoap[] emailAddresses, com.evolveum.polygon.connector.liferay.organization.OrgLaborSoap[] orgLabors, com.evolveum.polygon.connector.liferay.organization.PhoneSoap[] phones, com.evolveum.polygon.connector.liferay.organization.WebsiteSoap[] websites, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap addOrganization(long parentOrganizationId, java.lang.String name, java.lang.String type, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public void addPasswordPolicyOrganizations(long passwordPolicyId, long[] organizationIds) throws java.rmi.RemoteException;
    public void deleteLogo(long organizationId) throws java.rmi.RemoteException;
    public void deleteOrganization(long organizationId) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap[] getManageableOrganizations(java.lang.String actionId, int max) throws java.rmi.RemoteException;
    public long getOrganizationId(long companyId, java.lang.String name) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap getOrganization(long organizationId) throws java.rmi.RemoteException;
    public int getOrganizationsCount(long companyId, long parentOrganizationId) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap[] getOrganizations(long companyId, long parentOrganizationId) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap[] getOrganizations(long companyId, long parentOrganizationId, int start, int end) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap[] getUserOrganizations(long userId) throws java.rmi.RemoteException;
    public void setGroupOrganizations(long groupId, long[] organizationIds) throws java.rmi.RemoteException;
    public void unsetGroupOrganizations(long groupId, long[] organizationIds) throws java.rmi.RemoteException;
    public void unsetPasswordPolicyOrganizations(long passwordPolicyId, long[] organizationIds) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap updateOrganization(long organizationId, long parentOrganizationId, java.lang.String name, java.lang.String type, boolean recursable, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.AddressSoap[] addresses, com.evolveum.polygon.connector.liferay.organization.EmailAddressSoap[] emailAddresses, com.evolveum.polygon.connector.liferay.organization.OrgLaborSoap[] orgLabors, com.evolveum.polygon.connector.liferay.organization.PhoneSoap[] phones, com.evolveum.polygon.connector.liferay.organization.WebsiteSoap[] websites, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap updateOrganization(long organizationId, long parentOrganizationId, java.lang.String name, java.lang.String type, boolean recursable, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap updateOrganization(long organizationId, long parentOrganizationId, java.lang.String name, java.lang.String type, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.AddressSoap[] addresses, com.evolveum.polygon.connector.liferay.organization.EmailAddressSoap[] emailAddresses, com.evolveum.polygon.connector.liferay.organization.OrgLaborSoap[] orgLabors, com.evolveum.polygon.connector.liferay.organization.PhoneSoap[] phones, com.evolveum.polygon.connector.liferay.organization.WebsiteSoap[] websites, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
    public com.evolveum.polygon.connector.liferay.organization.OrganizationSoap updateOrganization(long organizationId, long parentOrganizationId, java.lang.String name, java.lang.String type, long regionId, long countryId, int statusId, java.lang.String comments, boolean site, com.evolveum.polygon.connector.liferay.organization.ServiceContext serviceContext) throws java.rmi.RemoteException;
}
